spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adoteumpet
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
flyway:
  locations:
    classpath: db/migration