#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/adoteumpet
#    username: postgres
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#
#flyway:
#  locations:
#    classpath: db/migration

spring:
  devtools:
    add-properties: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 30

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/adoteumpet
    username: postgres
    password: root

server:
  error:
    include-stacktrace: never
  port: 8080